### ISSUE TITLE
Links dos tutoriais estão fora do ar

### ISSUE THREAD

**Issue by maribernardes** [natandrade/Tutorial_Medical_Image_Registration#3]
Boa tarde, estava buscando material e exemplos de engenharia biomédica para complementar uma aula sobre transformações de corpos rígidos e me deparei com seu material no github. Fiquei bastante interessada, mas ao clicar nos links dos tutoriais, percebi que estão todos fora do ar.
Caso ainda tenha interesse em partilhar este material, favor entrar em contato: bernardes@unb.br

**Comment by natandrade** [comment]
Bom dia! Estarei ajustando assim q possível! Obrigado pelo aviso!
